#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import sys
import time
from pathlib import Path

from openai import OpenAI

from templates.system_prompts import ANALYST_SYSTEM, AUTHOR_SYSTEM, EDITOR_SYSTEM, SCOUT_SYSTEM
from utils import WORKSPACE, append_text, load_project_env, load_text, now_str, today_str, write_text

load_project_env()

RESEARCH_MODEL = os.getenv("RESEARCH_MODEL", "gpt-4o-mini")
WRITER_MODEL = os.getenv("WRITER_MODEL", "gpt-4o-mini")
EDITOR_MODEL = os.getenv("EDITOR_MODEL", WRITER_MODEL)
ISSUE_SLOT = os.getenv("ISSUE_SLOT", "").strip().lower()
RECENT_TOPIC_LIMIT = int(os.getenv("RECENT_TOPIC_LIMIT", "8"))
DUPLICATE_TITLE_THRESHOLD = float(os.getenv("DUPLICATE_TITLE_THRESHOLD", "0.60"))
AUTHOR_TOPIC_RETRIES = int(os.getenv("AUTHOR_TOPIC_RETRIES", "2"))
EDITOR_TOPIC_RETRIES = int(os.getenv("EDITOR_TOPIC_RETRIES", "3"))

ALLOWED = {"scout", "analyst", "author", "editor"}
MEMO_AGENTS = {"scout", "analyst"}
MARKDOWN_AGENTS = {"author", "editor"}
SYSTEMS = {"scout": SCOUT_SYSTEM, "analyst": ANALYST_SYSTEM, "author": AUTHOR_SYSTEM, "editor": EDITOR_SYSTEM}

# Minimum required sections — structural, not prescriptive.
# Em writes in whatever structure serves the piece.
# issue_contract.py enforces quality and substance; we only enforce
# the two hard-minimum structural anchors here to stay in sync.
# Matching is case-insensitive and ignores trailing punctuation so minor
# LLM formatting variations (e.g. "## CTA:" or "## cta") still pass.
REQUIRED_SECTIONS = [
    "## CTA",
    "## Sources",
]

# Hard reminder injected into every author/editor task prompt so the model
# cannot truncate or omit the closing sections even under retry pressure.
REQUIRED_SECTIONS_REMINDER = """
# REQUIRED OUTPUT STRUCTURE (non-negotiable)
Your response MUST end with these two sections, in this order, no matter how long the issue is:

## CTA
<1-2 paragraphs: what to try this week, subscribe URL, sponsor email>

## Sources
<bullet list of real URLs used>

Do NOT truncate the issue before reaching ## CTA and ## Sources.
""".strip()

BAD_CONTEXT_MARKERS = [
    "No concrete content returned",
    "Missing Content",
    "description incomplete in provided content",
    "Generated by [Your Name/Team]",
    "# Raw intel refresh",
]

# Any existing slot file with fewer than this many words is treated as a
# failed/incomplete draft and deleted before the author runs. Keeps a short
# stale draft from poisoning the next run's topic selection.
FAILED_DRAFT_WORD_FLOOR = 400

STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "for", "from", "how", "in", "into", "is", "it",
    "of", "on", "or", "the", "this", "to", "use", "using", "with", "your", "you", "managers", "manager",
    "operators", "operator", "solo", "ai", "forgecore", "newsletter", "issue", "brand", "brands",
}

class DuplicateTopicError(ValueError):
    pass


def issue_id() -> str:
    base = today_str()
    return f"{base}-{ISSUE_SLOT}" if ISSUE_SLOT in {"am", "pm"} else base


def slot_suffix() -> str:
    return f"-{ISSUE_SLOT}" if ISSUE_SLOT in {"am", "pm"} else ""


def issue_file() -> Path:
    return WORKSPACE / "content" / "issues" / f"{issue_id()}.md"


def scout_file() -> Path:
    return WORKSPACE / "research" / "raw" / f"RAW-INTEL-{today_str()}{slot_suffix()}.md"


def brief_file() -> Path:
    return WORKSPACE / "research" / "briefs" / f"EDITORIAL-BRIEF-{today_str()}{slot_suffix()}.md"


def progress(message: str) -> None:
    print(f"[progress] {message}", flush=True)
    append_text(WORKSPACE / "state" / "progress-log.md", f"[{now_str()}] {message}")


def warn(message: str) -> None:
    print(f"[warn] {message}", flush=True)
    append_text(WORKSPACE / "state" / "warnings.log", f"[{now_str()}] {message}")


def error(agent: str, message: str) -> None:
    print(f"[error:{agent}] {message}", file=sys.stderr, flush=True)
    append_text(WORKSPACE / "state" / "errors.log", f"[{now_str()}] {agent}: {message}")


def choose_model(agent: str) -> str:
    if agent in {"scout", "analyst"}:
        return RESEARCH_MODEL
    if agent == "editor":
        return EDITOR_MODEL
    return WRITER_MODEL


def title_from_markdown(text: str, fallback: str = "") -> str:
    """Return the first H1 title found anywhere in the document.

    Searching the whole text (not just the first line) means a single blank
    line or stray sentence before the title — a common LLM formatting hiccup —
    no longer causes a false-negative title miss.
    """
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and len(stripped) > 2:
            return stripped[2:].strip()
    return fallback


def topic_tokens(value: str) -> set[str]:
    tokens = set()
    for token in re.findall(r"[a-z0-9]+", value.lower()):
        if len(token) < 3 or token in STOPWORDS:
            continue
        tokens.add(token)
    return tokens


def topic_similarity(left: str, right: str) -> float:
    a = topic_tokens(left)
    b = topic_tokens(right)
    if not a or not b:
        return 0.0
    return len(a & b) / max(1, len(a | b))


def recent_issue_files(limit: int = RECENT_TOPIC_LIMIT) -> list[Path]:
    issues_dir = WORKSPACE / "content" / "issues"
    if not issues_dir.exists():
        return []
    current = issue_file().name
    files = [path for path in issues_dir.glob("*.md") if path.name != current]
    return sorted(files, key=lambda path: path.name, reverse=True)[:limit]


def recent_topic_context() -> str:
    lines: list[str] = []
    for path in recent_issue_files():
        text = load_text(path)
        title = title_from_markdown(text, path.stem)
        if not title:
            continue
        snippet = " ".join(line.strip() for line in text.splitlines()[1:12] if line.strip() and not line.startswith("## "))
        if len(snippet) > 260:
            snippet = snippet[:257].rsplit(" ", 1)[0] + "..."
        lines.append(f"- {path.name}: {title}" + (f" — {snippet}" if snippet else ""))
    return "\n".join(lines) if lines else "No recent published issues yet."


def affiliate_registry_context() -> str:
    path = WORKSPACE / "monetization" / "affiliate-registry.json"
    if not path.exists():
        return "Affiliate registry not found. Do not use affiliate or partner-link language."
    text = load_text(path)
    if len(text) > 6500:
        text = text[:6500] + "\n..."
    return (
        "Use this registry only as monetization guidance. Do not force affiliate links. "
        "Do not publish placeholder labels like AFFILIATE_CASTMAGIC as live links. "
        "If a listed tool fits, mention it only with disclosure, bad-fit warning, and a simpler alternative.\n\n"
        + text
    )


def enforce_not_duplicate_title(agent: str, markdown: str) -> None:
    if agent not in {"author", "editor"}:
        return
    title = title_from_markdown(markdown)
    if not title:
        return
    for path in recent_issue_files(limit=6):
        existing = title_from_markdown(load_text(path), path.stem)
        score = topic_similarity(title, existing)
        if score >= DUPLICATE_TITLE_THRESHOLD:
            raise DuplicateTopicError(
                f"{agent} generated a topic too similar to recent issue {path.name}: "
                f"'{title}' vs '{existing}' (similarity={score:.2f})"
            )


def clean_old_slot_file_for_author(agent: str) -> None:
    """Delete the current slot's issue file before the author runs if it looks
    like a failed draft. Two conditions trigger deletion:

    1. Contamination markers — placeholder/raw-intel text that must never be
       used as source material for a new draft.
    2. Below the failed-draft word floor — a short file left by a previous
       failed run (e.g. the validator bailed at 610 words) would otherwise be
       fed to the editor as CURRENT_SLOT_ISSUE_CONTEXT, causing it to re-anchor
       on the same thin/boring topic instead of starting fresh.
    """
    if agent != "author" or not issue_file().exists():
        return

    existing = load_text(issue_file())

    if any(marker.lower() in existing.lower() for marker in BAD_CONTEXT_MARKERS):
        issue_file().unlink()
        progress(f"Removed contaminated draft before author run: content/issues/{issue_id()}.md")
        return

    word_count = len(existing.split())
    if word_count < FAILED_DRAFT_WORD_FLOOR:
        issue_file().unlink()
        progress(
            f"Removed under-floor draft ({word_count} words < {FAILED_DRAFT_WORD_FLOOR}) "
            f"before author run: content/issues/{issue_id()}.md"
        )


def today_research_files() -> list[Path]:
    return sorted((WORKSPACE / "research" / "raw").glob(f"{today_str()}-*.md"))


def fresh_research_urls(limit: int = 8) -> list[str]:
    urls: list[str] = []
    seen: set[str] = set()
    for path in today_research_files():
        text = load_text(path)
        for match in re.finditer(r"^- URL:\s*(https?://\S+)", text, flags=re.MULTILINE):
            url = match.group(1).rstrip(").,")
            if url and url not in seen:
                seen.add(url)
                urls.append(url)
                if len(urls) >= limit:
                    return urls
    return urls


def ensure_memo_source_urls(agent: str, memo: str) -> str:
    urls = re.findall(r"https?://\S+", memo)
    if len(urls) >= 3:
        return memo

    source_urls = fresh_research_urls(limit=5)
    missing = [url for url in source_urls if url not in memo]
    if not missing:
        return memo

    appended = "\n\n## Deterministic Source URLs\n" + "\n".join(f"- {url}" for url in missing[:5]) + "\n"
    warn(f"{agent} memo included {len(urls)} source URLs; appended {min(len(missing), 5)} deterministic URLs from today's research")
    return memo.rstrip() + appended


def gather_research(budget: int = 14000) -> str:
    blocks: list[str] = []
    for path in today_research_files()[:10]:
        text = load_text(path)
        if text.strip():
            blocks.append(f"## {path.name}\n{text[:2400]}")
    if not blocks:
        raise RuntimeError("No fresh research files found for today. Run web_research.py successfully before agents.")
    return "\n\n".join(blocks)[:budget]


def load_fresh_scout() -> str:
    path = scout_file()
    if not path.exists():
        if ISSUE_SLOT in {"am", "pm"}:
            raise RuntimeError(f"Fresh scout memo missing for this slot: {path.as_posix()}. Run scout first.")
        fallback = WORKSPACE / "research" / "raw" / f"RAW-INTEL-{today_str()}.md"
        if fallback.exists():
            return load_text(fallback)
        raise RuntimeError(f"Fresh scout memo missing for today: {path.as_posix()}")
    return load_text(path)


def load_fresh_brief(required: bool) -> str:
    path = brief_file()
    if not path.exists():
        if required:
            raise RuntimeError(f"Fresh editorial brief missing for this slot: {path.as_posix()}. Run analyst first.")
        return "No editorial brief yet. Analyst should create it from today's fresh research and scout memo only."
    text = load_text(path)
    if any(marker.lower() in text.lower() for marker in BAD_CONTEXT_MARKERS):
        raise RuntimeError(f"Fresh editorial brief is contaminated: {path.as_posix()}")
    return text


def current_issue_context(agent: str) -> str:
    if agent == "author":
        return "No existing draft. Write a clean original issue from today's research and editorial brief only."
    if issue_file().exists():
        text = load_text(issue_file())
        if any(marker.lower() in text.lower() for marker in BAD_CONTEXT_MARKERS):
            return "Existing draft is contaminated and must be ignored. Rewrite a clean complete issue from today's research and brief only."
        return text[:9000]
    return "No existing draft for this slot."


def duplicate_retry_context(rejections: list[str]) -> str:
    if not rejections:
        return ""
    bullets = "\n".join(f"- {item}" for item in rejections[-3:])
    return (
        "\n\n# REJECTED DUPLICATE TOPICS FROM THIS RUN\n"
        "The following draft topics were rejected as too similar to recent issues. Do not use the same source angle, keywords, or job-to-be-done again. Choose a materially different research item and operator workflow.\n"
        f"{bullets}\n"
        "Good alternate directions from today's research may include: Zapier Agents vs ChatGPT workspace agents, MuleSoft pricing decision, advanced account security, AI cybersecurity workflow, browser/tool selection, or share-of-voice tracking if it is clearly not AEO competitor analysis."
    )


def context(agent: str, extra_context: str = "") -> str:
    # On duplicate retries, extra_context is non-empty. Reserve ~2000 chars of headroom
    # by tightening the research budget so the total prompt stays well under the context limit.
    research_budget = 10000 if extra_context.strip() else 14000
    research = gather_research(budget=research_budget)
    brief_required = agent in {"author", "editor"}
    parts = [
        f"# TIMESTAMP\n{now_str()}",
        f"# ISSUE_SLOT\n{ISSUE_SLOT or 'default'}",
        f"# ISSUE_ID\n{issue_id()}",
        f"# TARGET_ISSUE_PATH\ncontent/issues/{issue_id()}.md",
        f"# TARGET_SCOUT_PATH\n{scout_file().relative_to(WORKSPACE).as_posix()}",
        f"# TARGET_BRIEF_PATH\n{brief_file().relative_to(WORKSPACE).as_posix()}",
        f"# CRITICAL CONTEXT RULE\nUse only today's fresh research files and the deterministic slot-specific scout/brief files above. Do not copy, summarize, or improve old broken issue files. If context contains placeholder or missing-content language, treat it as a defect to avoid, not source material.",
        f"# DUPLICATE TOPIC AVOIDANCE\nDo not choose, brief, draft, or polish a topic that substantially overlaps with any recent issue below. If today's strongest source matches a recent topic, choose a different source, persona, job-to-be-done, tool category, or workflow angle.\n{recent_topic_context()}",
        f"# MONETIZATION REGISTRY\n{affiliate_registry_context()}",
        extra_context.strip(),
        f"# GOALS\n{load_text(WORKSPACE / 'GOALS.md')}",
        f"# RULES\n{load_text(WORKSPACE / 'AGENTS.md')}",
        f"# SOUL\n{load_text(WORKSPACE / 'agents' / agent / 'SOUL.md')}",
        f"# MEMORY\n{load_text(WORKSPACE / 'agents' / agent / 'MEMORY.md')}",
        f"# FRESH_RESEARCH_ITEMS\n{research}",
    ]
    if agent == "analyst":
        parts.append(f"# FRESH_SCOUT_MEMO\n{load_fresh_scout()[:7000]}")
    if agent in {"author", "editor"}:
        parts.append(f"# EM'S EDITORIAL VOICE\n{load_text(WORKSPACE / 'em' / 'VOICE.md')}")
        parts.append(f"# FRESH_BRIEF\n{load_fresh_brief(required=brief_required)[:7000]}")
    else:
        parts.append(f"# BRIEF_STATUS\n{load_fresh_brief(required=False)[:1200]}")
    parts.append(f"# CURRENT_SLOT_ISSUE_CONTEXT\n{current_issue_context(agent)}")
    return "\n\n".join(part for part in parts if part)[:24000]


def openai_client() -> OpenAI:
    return OpenAI()


def call_text_model(
    model: str,
    user_prompt: str,
    *,
    temperature: float,
    system_prompt: str | None = None,
) -> str:
    """Call the OpenAI chat completions API.

    When system_prompt is provided it is sent as a separate system message
    so it is not competing for space with the user context block. This is
    critical for long AUTHOR_SYSTEM / EDITOR_SYSTEM prompts — without the
    split the combined single-user-message prompt exceeds gpt-4o's practical
    limit and the model returns near-empty responses.
    """
    messages: list[dict] = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": user_prompt})
    result = openai_client().chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
    )
    return (result.choices[0].message.content or "").strip()


def build_memo_prompt(agent: str) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for memo agents (scout, analyst)."""
    if agent == "scout":
        task = (
            f"Write a fresh Markdown scout memo for {scout_file().relative_to(WORKSPACE).as_posix()}. "
            "Your response MUST start with a # heading on the very first line. "
            "Return ONLY Markdown, never JSON. Rank 3-5 operator-first topic angles from today's research, "
            "name the strongest angle, identify one Tool of the Week candidate, list source URLs, and explain why the topic helps solo operators save time, automate work, make money, or avoid bad tools. "
            "Reject any angle that overlaps with the recent published issues listed in context. Use the monetization registry only to identify natural fit; do not force affiliate mentions."
        )
    elif agent == "analyst":
        task = (
            f"Write a fresh Markdown editorial brief for {brief_file().relative_to(WORKSPACE).as_posix()}. "
            "Your response MUST start with a # heading on the very first line — use the working headline as your # title. "
            "Return ONLY Markdown, never JSON. Use today's scout memo and research only. "
            "Include: working headline (as # title), target operator, job-to-be-done, thesis, why now, workflow outline (3-6 steps), tool stack, tradeoffs, monetization fit, CTA direction, and source URLs. "
            "Do not brief a topic already covered in recent published issues. "
            "Be opinionated — if the scout's top angle is weaker than a secondary one, say so and switch. "
            "Use approved monetization only when the registry says the tool fits the job-to-be-done."
        )
    else:
        raise ValueError(f"Unsupported memo agent: {agent}")

    user_prompt = f"Task:\n{task}\n\nContext:\n{context(agent)}"
    return SYSTEMS[agent], user_prompt


def build_markdown_prompt(agent: str, extra_context: str = "") -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for markdown agents (author, editor)."""
    target = f"content/issues/{issue_id()}.md"
    if agent == "author":
        task = (
            f"Write a clean, original, complete newsletter issue as Markdown for {target}. "
            "Return ONLY Markdown. Use today's research and the fresh slot-specific brief only. "
            "Do not reuse old issue text. Do not choose a topic that overlaps with recent published issues. "
            "If an approved affiliate candidate genuinely fits, you may mention it with disclosure, bad-fit warning, and a simpler alternative, "
            "but do not publish placeholder affiliate labels as live links. "
            "Do not include placeholder phrases like 'No concrete content returned', 'Missing Content', or 'description incomplete'. "
            "Do not wrap it in JSON or code fences.\n\n"
            + REQUIRED_SECTIONS_REMINDER
        )
    else:
        task = (
            f"Edit the existing draft for {target}. "
            "Do not change the title or core topic unless the current draft is contaminated. "
            "If the draft already passed Author validation, preserve its selected topic and only improve clarity, structure, specificity, and usefulness. "
            "Return ONLY the complete final Markdown issue. "
            "Keep monetization transparent and registry-approved; remove forced or placeholder affiliate language. "
            "Prefer preserving or expanding useful detail; do not shorten the issue unless removing junk.\n\n"
            + REQUIRED_SECTIONS_REMINDER
        )
    user_prompt = f"Task:\n{task}\n\nContext:\n{context(agent, extra_context=extra_context)}"
    return SYSTEMS[agent], user_prompt


def clean_markdown(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```markdown"):
        cleaned = cleaned[len("```markdown"):].strip()
    elif cleaned.startswith("```"):
        cleaned = cleaned[3:].strip()
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()
    return cleaned + "\n"


def section_present(text: str, section: str) -> bool:
    """Check for a required section header, tolerating trailing punctuation and
    case differences that LLMs occasionally introduce (e.g. '## CTA:' or '## cta')."""
    needle = section.rstrip(":").lower()
    for line in text.splitlines():
        if line.startswith("##"):
            candidate = line.rstrip(":").lower()
            if candidate == needle:
                return True
    return False


def ensure_markdown_title(agent: str, text: str) -> str:
    """Guarantee the document starts with a valid # Title line."""
    lines = text.splitlines()

    if lines and lines[0].strip().startswith("# ") and len(lines[0].strip()) > 2:
        return text

    title_index = next(
        (i for i, line in enumerate(lines) if line.strip().startswith("# ") and len(line.strip()) > 2),
        None,
    )

    if title_index is not None:
        warn(
            f"{agent} response had {title_index} line(s) before the # title; "
            "stripping preamble so title is the first line"
        )
        return "\n".join(lines[title_index:]) + "\n"

    slot_label = f" ({ISSUE_SLOT.upper()})" if ISSUE_SLOT in {"am", "pm"} else ""
    fallback_title = f"# ForgeCore AI — {today_str()}{slot_label}"
    warn(
        f"{agent} returned no # title — injecting deterministic fallback: {fallback_title}"
    )
    return fallback_title + "\n\n" + text


def inject_missing_boilerplate_sections(agent: str, text: str) -> str:
    """Deterministically append any missing boilerplate sections the model dropped."""
    primary_cta_text = os.getenv("PRIMARY_CTA_TEXT", "Read ForgeCore AI — written by Em")
    primary_cta_url = os.getenv("PRIMARY_CTA_URL", "https://news.forgecore.co")
    sponsor_email = os.getenv("SPONSOR_EMAIL", "sponsors@forgecore.co")

    result = text.rstrip()

    if not section_present(result, "## CTA"):
        warn(f"{agent} dropped ## CTA — injecting deterministic fallback")
        result += (
            f"\n\n## CTA\n\n"
            f"If this was useful, forward it to one operator who needs it this week. "
            f"[{primary_cta_text}]({primary_cta_url})\n\n"
            f"Interested in reaching ForgeCore AI readers? Email [{sponsor_email}](mailto:{sponsor_email})."
        )

    if not section_present(result, "## Sources"):
        warn(f"{agent} dropped ## Sources — injecting deterministic fallback from today's research")
        source_urls = fresh_research_urls(limit=5)
        if source_urls:
            bullets = "\n".join(f"- {url}" for url in source_urls)
        else:
            bullets = "- Sources gathered from today's research feed"
        result += f"\n\n## Sources\n\n{bullets}"

    return result + "\n"


def validate_markdown(agent: str, text: str) -> None:
    lower = text.lower()
    for marker in BAD_CONTEXT_MARKERS:
        if marker.lower() in lower:
            raise ValueError(f"{agent} returned contaminated placeholder/raw-intel marker: {marker}")
    if not text.strip().startswith("# "):
        raise ValueError(f"{agent} did not return a Markdown issue title")
    missing = [section for section in REQUIRED_SECTIONS if not section_present(text, section)]
    if missing:
        raise ValueError(f"{agent} Markdown missing required sections: {', '.join(missing)}")

    enforce_not_duplicate_title(agent, text)

    words = len(text.split())
    hard_floor = 400
    soft_floor = 650
    if words < hard_floor:
        raise ValueError(f"{agent} Markdown too short to be a real draft: {words} words (minimum {hard_floor})")
    if words < soft_floor:
        warn(f"{agent} draft is short ({words} words, target {soft_floor}+); passing to editor to expand")


def validate_memo(agent: str, text: str) -> None:
    lower = text.lower()

    if not text.strip().startswith("#"):
        raise ValueError(f"{agent} memo did not return Markdown with a title")

    for marker in BAD_CONTEXT_MARKERS:
        if marker.lower() in lower:
            raise ValueError(f"{agent} memo returned contaminated marker: {marker}")

    if "{\"" in text or '"files"' in text or '"summary"' in text:
        raise ValueError(f"{agent} memo returned JSON-like control text")

    urls = re.findall(r"https?://\S+", text)
    min_words = 180 if agent == "scout" else 250

    if len(text.split()) < min_words:
        raise ValueError(f"{agent} memo too short: {len(text.split())} words")

    if len(urls) < 3:
        raise ValueError(f"{agent} memo needs at least 3 source URLs")


def max_topic_retries(agent: str) -> int:
    if agent == "author":
        return AUTHOR_TOPIC_RETRIES
    if agent == "editor":
        return EDITOR_TOPIC_RETRIES
    return 0


def generate_markdown_with_duplicate_retries(agent: str, model: str) -> str:
    rejections: list[str] = []
    original_valid_draft = ""
    if agent == "editor" and issue_file().exists():
        candidate = load_text(issue_file())
        try:
            validate_markdown("author", candidate)
            original_valid_draft = candidate
        except Exception as exc:
            warn(f"editor fallback draft is not valid enough to preserve: {type(exc).__name__}: {exc}")

    attempts = max(1, max_topic_retries(agent) + 1)
    for attempt in range(1, attempts + 1):
        extra = duplicate_retry_context(rejections)
        system_prompt, user_prompt = build_markdown_prompt(agent, extra_context=extra)
        temperature = 0.45 if agent == "editor" else (0.35 if rejections else 0.30)
        raw = clean_markdown(
            call_text_model(model, user_prompt, temperature=temperature, system_prompt=system_prompt)
        )
        raw = ensure_markdown_title(agent, raw)
        markdown = inject_missing_boilerplate_sections(agent, raw)
        try:
            validate_markdown(agent, markdown)
            if rejections:
                warn(f"{agent} recovered from duplicate-topic rejection on attempt {attempt}")
            return markdown
        except DuplicateTopicError as exc:
            rejections.append(str(exc))
            warn(f"{agent} duplicate-topic rejection on attempt {attempt}/{attempts}: {exc}")
            if attempt >= attempts:
                if original_valid_draft:
                    warn("editor exhausted duplicate-topic retries; preserving valid Author draft and passing it to improvement loop")
                    return original_valid_draft
                raise
    raise RuntimeError(f"{agent} failed duplicate-topic recovery")


def run(agent: str) -> int:
    start = time.time()
    model = choose_model(agent)
    progress(f"[{agent}] Starting with {model} (issue={issue_id()})")
    try:
        clean_old_slot_file_for_author(agent)
        if agent in MEMO_AGENTS:
            memo_temp = 0.25 if agent == "scout" else 0.30
            system_prompt, user_prompt = build_memo_prompt(agent)
            memo = clean_markdown(
                call_text_model(model, user_prompt, temperature=memo_temp, system_prompt=system_prompt)
            )
            memo = ensure_memo_source_urls(agent, memo)
            validate_memo(agent, memo)

            path = scout_file() if agent == "scout" else brief_file()
            write_text(path, memo)

            count = 1
            summary = f"Wrote Markdown {agent} memo to {path.relative_to(WORKSPACE).as_posix()}"

        elif agent in MARKDOWN_AGENTS:
            markdown = generate_markdown_with_duplicate_retries(agent, model)
            write_text(issue_file(), markdown)

            count = 1
            summary = f"Wrote clean Markdown issue to content/issues/{issue_id()}.md"

        else:
            raise ValueError(f"Unsupported agent: {agent}")
        progress(f"{agent}: {summary} (files={count}, duration={time.time() - start:.2f}s)")
        return 0
    except Exception as exc:
        error(agent, f"{type(exc).__name__}: {exc}")
        return 1


def main() -> int:
    if not os.getenv("OPENAI_API_KEY"):
        print("OPENAI_API_KEY is not set in GitHub Actions secrets.", file=sys.stderr)
        return 1
    if len(sys.argv) != 2 or sys.argv[1] not in ALLOWED:
        print("Usage: agent_loop.py <scout|analyst|author|editor>", file=sys.stderr)
        return 1
    return run(sys.argv[1])


if __name__ == "__main__":
    raise SystemExit(main())
