#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import sys
import time
from pathlib import Path

from openai import OpenAI

from templates.system_prompts import ANALYST_SYSTEM, AUTHOR_SYSTEM, EDITOR_SYSTEM, SCOUT_SYSTEM
from utils import WORKSPACE, append_text, load_project_env, load_text, now_str, today_str, write_text

load_project_env()

RESEARCH_MODEL = os.getenv("RESEARCH_MODEL", "gpt-4o-mini")
WRITER_MODEL = os.getenv("WRITER_MODEL", "gpt-4o-mini")
EDITOR_MODEL = os.getenv("EDITOR_MODEL", WRITER_MODEL)
ISSUE_SLOT = os.getenv("ISSUE_SLOT", "").strip().lower()
RECENT_TOPIC_LIMIT = int(os.getenv("RECENT_TOPIC_LIMIT", "8"))
DUPLICATE_TITLE_THRESHOLD = float(os.getenv("DUPLICATE_TITLE_THRESHOLD", "0.72"))
AUTHOR_TOPIC_RETRIES = int(os.getenv("AUTHOR_TOPIC_RETRIES", "2"))

ALLOWED = {"scout", "analyst", "author", "editor"}
MEMO_AGENTS = {"scout", "analyst"}
MARKDOWN_AGENTS = {"author", "editor"}
SYSTEMS = {"scout": SCOUT_SYSTEM, "analyst": ANALYST_SYSTEM, "author": AUTHOR_SYSTEM, "editor": EDITOR_SYSTEM}

REQUIRED_SECTIONS = [
    "## Hook",
    "## Top Story",
    "## Why It Matters",
    "## Highlights",
    "## Tool of the Week",
    "## Workflow",
    "## CTA",
    "## Sources",
]

BAD_CONTEXT_MARKERS = [
    "No concrete content returned",
    "Missing Content",
    "description incomplete in provided content",
    "Generated by [Your Name/Team]",
    "# Raw intel refresh",
]

STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "for", "from", "how", "in", "into", "is", "it",
    "of", "on", "or", "the", "this", "to", "use", "using", "with", "your", "you", "managers", "manager",
    "operators", "operator", "solo", "ai", "forgecore", "newsletter", "issue", "brand", "brands",
}

class DuplicateTopicError(ValueError):
    pass


def issue_id() -> str:
    base = today_str()
    return f"{base}-{ISSUE_SLOT}" if ISSUE_SLOT in {"am", "pm"} else base


def slot_suffix() -> str:
    return f"-{ISSUE_SLOT}" if ISSUE_SLOT in {"am", "pm"} else ""


def issue_file() -> Path:
    return WORKSPACE / "content" / "issues" / f"{issue_id()}.md"


def scout_file() -> Path:
    return WORKSPACE / "research" / "raw" / f"RAW-INTEL-{today_str()}{slot_suffix()}.md"


def brief_file() -> Path:
    return WORKSPACE / "research" / "briefs" / f"EDITORIAL-BRIEF-{today_str()}{slot_suffix()}.md"


def progress(message: str) -> None:
    print(f"[progress] {message}", flush=True)
    append_text(WORKSPACE / "state" / "progress-log.md", f"[{now_str()}] {message}")


def warn(message: str) -> None:
    print(f"[warn] {message}", flush=True)
    append_text(WORKSPACE / "state" / "warnings.log", f"[{now_str()}] {message}")


def error(agent: str, message: str) -> None:
    print(f"[error:{agent}] {message}", file=sys.stderr, flush=True)
    append_text(WORKSPACE / "state" / "errors.log", f"[{now_str()}] {agent}: {message}")


def choose_model(agent: str) -> str:
    if agent in {"scout", "analyst"}:
        return RESEARCH_MODEL
    if agent == "editor":
        return EDITOR_MODEL
    return WRITER_MODEL


def title_from_markdown(text: str, fallback: str = "") -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def topic_tokens(value: str) -> set[str]:
    tokens = set()
    for token in re.findall(r"[a-z0-9]+", value.lower()):
        if len(token) < 3 or token in STOPWORDS:
            continue
        tokens.add(token)
    return tokens


def topic_similarity(left: str, right: str) -> float:
    a = topic_tokens(left)
    b = topic_tokens(right)
    if not a or not b:
        return 0.0
    return len(a & b) / max(1, len(a | b))


def recent_issue_files(limit: int = RECENT_TOPIC_LIMIT) -> list[Path]:
    issues_dir = WORKSPACE / "content" / "issues"
    if not issues_dir.exists():
        return []
    current = issue_file().name
    files = [path for path in issues_dir.glob("*.md") if path.name != current]
    return sorted(files, key=lambda path: path.name, reverse=True)[:limit]


def recent_topic_context() -> str:
    lines: list[str] = []
    for path in recent_issue_files():
        text = load_text(path)
        title = title_from_markdown(text, path.stem)
        if not title:
            continue
        snippet = " ".join(line.strip() for line in text.splitlines()[1:12] if line.strip() and not line.startswith("## "))
        if len(snippet) > 260:
            snippet = snippet[:257].rsplit(" ", 1)[0] + "..."
        lines.append(f"- {path.name}: {title}" + (f" — {snippet}" if snippet else ""))
    return "\n".join(lines) if lines else "No recent published issues yet."


def affiliate_registry_context() -> str:
    path = WORKSPACE / "monetization" / "affiliate-registry.json"
    if not path.exists():
        return "Affiliate registry not found. Do not use affiliate or partner-link language."
    text = load_text(path)
    if len(text) > 6500:
        text = text[:6500] + "\n..."
    return (
        "Use this registry only as monetization guidance. Do not force affiliate links. "
        "Do not publish placeholder labels like AFFILIATE_CASTMAGIC as live links. "
        "If a listed tool fits, mention it only with disclosure, bad-fit warning, and a simpler alternative.\n\n"
        + text
    )


def enforce_not_duplicate_title(agent: str, markdown: str) -> None:
    if agent not in {"author", "editor"}:
        return
    title = title_from_markdown(markdown)
    if not title:
        return
    for path in recent_issue_files(limit=6):
        existing = title_from_markdown(load_text(path), path.stem)
        score = topic_similarity(title, existing)
        if score >= DUPLICATE_TITLE_THRESHOLD:
            raise DuplicateTopicError(
                f"{agent} generated a topic too similar to recent issue {path.name}: "
                f"'{title}' vs '{existing}' (similarity={score:.2f})"
            )


def clean_old_slot_file_for_author(agent: str) -> None:
    # A generation run must start clean. Do not let previous failed drafts become context.
    if agent == "author" and issue_file().exists():
        existing = load_text(issue_file())
        if any(marker.lower() in existing.lower() for marker in BAD_CONTEXT_MARKERS):
            issue_file().unlink()
            progress(f"Removed contaminated draft before author run: content/issues/{issue_id()}.md")


def today_research_files() -> list[Path]:
    return sorted((WORKSPACE / "research" / "raw").glob(f"{today_str()}-*.md"))


def fresh_research_urls(limit: int = 8) -> list[str]:
    urls: list[str] = []
    seen: set[str] = set()
    for path in today_research_files():
        text = load_text(path)
        for match in re.finditer(r"^- URL:\s*(https?://\S+)", text, flags=re.MULTILINE):
            url = match.group(1).rstrip(").,")
            if url and url not in seen:
                seen.add(url)
                urls.append(url)
                if len(urls) >= limit:
                    return urls
    return urls


def ensure_memo_source_urls(agent: str, memo: str) -> str:
    urls = re.findall(r"https?://\S+", memo)
    if len(urls) >= 3:
        return memo

    source_urls = fresh_research_urls(limit=5)
    missing = [url for url in source_urls if url not in memo]
    if not missing:
        return memo

    appended = "\n\n## Deterministic Source URLs\n" + "\n".join(f"- {url}" for url in missing[:5]) + "\n"
    warn(f"{agent} memo included {len(urls)} source URLs; appended {min(len(missing), 5)} deterministic URLs from today's research")
    return memo.rstrip() + appended


def gather_research() -> str:
    blocks: list[str] = []
    for path in today_research_files()[:10]:
        text = load_text(path)
        if text.strip():
            blocks.append(f"## {path.name}\n{text[:2400]}")
    if not blocks:
        raise RuntimeError("No fresh research files found for today. Run web_research.py successfully before agents.")
    return "\n\n".join(blocks)


def load_fresh_scout() -> str:
    path = scout_file()
    if not path.exists():
        if ISSUE_SLOT in {"am", "pm"}:
            raise RuntimeError(f"Fresh scout memo missing for this slot: {path.as_posix()}. Run scout first.")
        fallback = WORKSPACE / "research" / "raw" / f"RAW-INTEL-{today_str()}.md"
        if fallback.exists():
            return load_text(fallback)
        raise RuntimeError(f"Fresh scout memo missing for today: {path.as_posix()}")
    return load_text(path)


def load_fresh_brief(required: bool) -> str:
    path = brief_file()
    if not path.exists():
        if required:
            raise RuntimeError(f"Fresh editorial brief missing for this slot: {path.as_posix()}. Run analyst first.")
        return "No editorial brief yet. Analyst should create it from today's fresh research and scout memo only."
    text = load_text(path)
    if any(marker.lower() in text.lower() for marker in BAD_CONTEXT_MARKERS):
        raise RuntimeError(f"Fresh editorial brief is contaminated: {path.as_posix()}")
    return text


def current_issue_context(agent: str) -> str:
    if agent == "author":
        return "No existing draft. Write a clean original issue from today's research and editorial brief only."
    if issue_file().exists():
        text = load_text(issue_file())
        if any(marker.lower() in text.lower() for marker in BAD_CONTEXT_MARKERS):
            return "Existing draft is contaminated and must be ignored. Rewrite a clean complete issue from today's research and brief only."
        return text[:9000]
    return "No existing draft for this slot."


def duplicate_retry_context(rejections: list[str]) -> str:
    if not rejections:
        return ""
    bullets = "\n".join(f"- {item}" for item in rejections[-3:])
    return (
        "\n\n# REJECTED DUPLICATE TOPICS FROM THIS RUN\n"
        "The following draft topics were rejected as too similar to recent issues. Do not use the same source angle, keywords, or job-to-be-done again. Choose a materially different research item and operator workflow.\n"
        f"{bullets}\n"
        "Good alternate directions from today's research may include: Zapier Agents vs ChatGPT workspace agents, MuleSoft pricing decision, advanced account security, AI cybersecurity workflow, browser/tool selection, or share-of-voice tracking if it is clearly not AEO competitor analysis."
    )


def context(agent: str, extra_context: str = "") -> str:
    research = gather_research()
    brief_required = agent in {"author", "editor"}
    parts = [
        f"# TIMESTAMP\n{now_str()}",
        f"# ISSUE_SLOT\n{ISSUE_SLOT or 'default'}",
        f"# ISSUE_ID\n{issue_id()}",
        f"# TARGET_ISSUE_PATH\ncontent/issues/{issue_id()}.md",
        f"# TARGET_SCOUT_PATH\n{scout_file().relative_to(WORKSPACE).as_posix()}",
        f"# TARGET_BRIEF_PATH\n{brief_file().relative_to(WORKSPACE).as_posix()}",
        f"# CRITICAL CONTEXT RULE\nUse only today's fresh research files and the deterministic slot-specific scout/brief files above. Do not copy, summarize, or improve old broken issue files. If context contains placeholder or missing-content language, treat it as a defect to avoid, not source material.",
        f"# DUPLICATE TOPIC AVOIDANCE\nDo not choose, brief, draft, or polish a topic that substantially overlaps with any recent issue below. If today's strongest source matches a recent topic, choose a different source, persona, job-to-be-done, tool category, or workflow angle.\n{recent_topic_context()}",
        f"# MONETIZATION REGISTRY\n{affiliate_registry_context()}",
        extra_context.strip(),
        f"# GOALS\n{load_text(WORKSPACE / 'GOALS.md')}",
        f"# RULES\n{load_text(WORKSPACE / 'AGENTS.md')}",
        f"# SOUL\n{load_text(WORKSPACE / 'agents' / agent / 'SOUL.md')}",
        f"# MEMORY\n{load_text(WORKSPACE / 'agents' / agent / 'MEMORY.md')}",
        f"# FRESH_RESEARCH_ITEMS\n{research[:14000]}",
    ]
    if agent == "analyst":
        parts.append(f"# FRESH_SCOUT_MEMO\n{load_fresh_scout()[:7000]}")
    if agent in {"author", "editor"}:
        parts.append(f"# FRESH_BRIEF\n{load_fresh_brief(required=brief_required)[:7000]}")
    else:
        parts.append(f"# BRIEF_STATUS\n{load_fresh_brief(required=False)[:1200]}")
    parts.append(f"# CURRENT_SLOT_ISSUE_CONTEXT\n{current_issue_context(agent)}")
    return "\n\n".join(part for part in parts if part)[:24000]


def openai_client() -> OpenAI:
    return OpenAI()


def call_text_model(model: str, prompt: str, *, temperature: float) -> str:
    result = openai_client().chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
    )
    return (result.choices[0].message.content or "").strip()


def build_memo_prompt(agent: str) -> str:
    if agent == "scout":
        task = (
            f"Write a fresh Markdown scout memo for {scout_file().relative_to(WORKSPACE).as_posix()}. "
            "Return ONLY Markdown, never JSON. Rank 3-5 operator-first topic angles from today's research, "
            "name the strongest angle, identify one Tool of the Week candidate, list source URLs, and explain why the topic helps solo operators save time, automate work, make money, or avoid bad tools. "
            "Reject any angle that overlaps with the recent published issues listed in context. Use the monetization registry only to identify natural fit; do not force affiliate mentions."
        )
    elif agent == "analyst":
        task = (
            f"Write a fresh Markdown editorial brief for {brief_file().relative_to(WORKSPACE).as_posix()}. "
            "Return ONLY Markdown, never JSON. Use today's scout memo and research only. Include: thesis, audience/persona, job-to-be-done, why now, section plan, workflow outline, tool recommendation, tradeoffs, CTA direction, and source URLs. "
            "Do not brief a topic already covered in recent published issues. Use approved monetization only when the registry says the tool fits the job-to-be-done."
        )
    else:
        raise ValueError(f"Unsupported memo agent: {agent}")

    return SYSTEMS[agent] + f"\n\nTask:\n{task}\n\nContext:\n{context(agent)}"


def build_markdown_prompt(agent: str, extra_context: str = "") -> str:
    target = f"content/issues/{issue_id()}.md"
    if agent == "author":
        task = f"Write a clean, original, complete newsletter issue as Markdown for {target}. Return ONLY Markdown. Use today's research and the fresh slot-specific brief only. Do not reuse old issue text. Do not choose a topic that overlaps with recent published issues. If an approved affiliate candidate genuinely fits, you may mention it with disclosure, bad-fit warning, and a simpler alternative, but do not publish placeholder affiliate labels as live links. Do not include placeholder phrases like 'No concrete content returned', 'Missing Content', or 'description incomplete'. Do not wrap it in JSON or code fences."
    else:
        task = f"Edit the existing draft for {target}. If it contains placeholder or raw-intel junk, rewrite it completely from today's research and fresh slot-specific brief. Return ONLY the complete final Markdown issue. Preserve the selected non-duplicate topic. Keep monetization transparent and registry-approved; remove forced or placeholder affiliate language. Prefer preserving or expanding useful detail; do not shorten the issue unless removing junk."
    return SYSTEMS[agent] + f"\n\nTask:\n{task}\n\nContext:\n{context(agent, extra_context=extra_context)}"


def clean_markdown(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```markdown"):
        cleaned = cleaned[len("```markdown"):].strip()
    elif cleaned.startswith("```"):
        cleaned = cleaned[3:].strip()
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()
    return cleaned + "\n"


def validate_markdown(agent: str, text: str) -> None:
    lower = text.lower()
    for marker in BAD_CONTEXT_MARKERS:
        if marker.lower() in lower:
            raise ValueError(f"{agent} returned contaminated placeholder/raw-intel marker: {marker}")
    if not text.strip().startswith("# "):
        raise ValueError(f"{agent} did not return a Markdown issue title")
    missing = [section for section in REQUIRED_SECTIONS if section not in text]
    if missing:
        raise ValueError(f"{agent} Markdown missing required sections: {', '.join(missing)}")

    enforce_not_duplicate_title(agent, text)

    words = len(text.split())
    # Author should create a full draft. Editor may produce a recoverable short draft;
    # the critic/improvement loop and quality gate own final publish enforcement.
    min_words = 650 if agent == "author" else 500
    if words < min_words:
        raise ValueError(f"{agent} Markdown too short: {words} words")
    if agent == "editor" and words < 650:
        warn(f"editor draft is short but recoverable ({words} words); passing to improvement loop")


def validate_memo(agent: str, text: str) -> None:
    lower = text.lower()

    if not text.strip().startswith("#"):
        raise ValueError(f"{agent} memo did not return Markdown with a title")

    for marker in BAD_CONTEXT_MARKERS:
        if marker.lower() in lower:
            raise ValueError(f"{agent} memo returned contaminated marker: {marker}")

    if "{\"" in text or '"files"' in text or '"summary"' in text:
        raise ValueError(f"{agent} memo returned JSON-like control text")

    urls = re.findall(r"https?://\S+", text)
    min_words = 180 if agent == "scout" else 250

    if len(text.split()) < min_words:
        raise ValueError(f"{agent} memo too short: {len(text.split())} words")

    if len(urls) < 3:
        raise ValueError(f"{agent} memo needs at least 3 source URLs")


def generate_markdown_with_duplicate_retries(agent: str, model: str) -> str:
    rejections: list[str] = []
    attempts = max(1, AUTHOR_TOPIC_RETRIES + 1) if agent == "author" else 1
    for attempt in range(1, attempts + 1):
        extra = duplicate_retry_context(rejections)
        markdown = clean_markdown(call_text_model(model, build_markdown_prompt(agent, extra_context=extra), temperature=0.35 if rejections else 0.25))
        try:
            validate_markdown(agent, markdown)
            if rejections:
                warn(f"{agent} recovered from duplicate-topic rejection on attempt {attempt}")
            return markdown
        except DuplicateTopicError as exc:
            rejections.append(str(exc))
            warn(f"{agent} duplicate-topic rejection on attempt {attempt}/{attempts}: {exc}")
            if attempt >= attempts:
                raise
    raise RuntimeError(f"{agent} failed duplicate-topic recovery")


def run(agent: str) -> int:
    start = time.time()
    model = choose_model(agent)
    progress(f"[{agent}] Starting with {model} (issue={issue_id()})")
    try:
        clean_old_slot_file_for_author(agent)
        if agent in MEMO_AGENTS:
            memo = clean_markdown(call_text_model(model, build_memo_prompt(agent), temperature=0.15))
            memo = ensure_memo_source_urls(agent, memo)
            validate_memo(agent, memo)

            path = scout_file() if agent == "scout" else brief_file()
            write_text(path, memo)

            count = 1
            summary = f"Wrote Markdown {agent} memo to {path.relative_to(WORKSPACE).as_posix()}"

        elif agent in MARKDOWN_AGENTS:
            markdown = generate_markdown_with_duplicate_retries(agent, model)
            write_text(issue_file(), markdown)

            count = 1
            summary = f"Wrote clean Markdown issue to content/issues/{issue_id()}.md"

        else:
            raise ValueError(f"Unsupported agent: {agent}")
        progress(f"{agent}: {summary} (files={count}, duration={time.time() - start:.2f}s)")
        return 0
    except Exception as exc:
        error(agent, f"{type(exc).__name__}: {exc}")
        return 1


def main() -> int:
    if not os.getenv("OPENAI_API_KEY"):
        print("OPENAI_API_KEY is not set in GitHub Actions secrets.", file=sys.stderr)
        return 1
    if len(sys.argv) != 2 or sys.argv[1] not in ALLOWED:
        print("Usage: agent_loop.py <scout|analyst|author|editor>", file=sys.stderr)
        return 1
    return run(sys.argv[1])


if __name__ == "__main__":
    raise SystemExit(main())
