#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import sys
import shutil
import time
from pathlib import Path

from openai import OpenAI

from templates.system_prompts import ANALYST_SYSTEM, AUTHOR_SYSTEM, EDITOR_SYSTEM, SCOUT_SYSTEM
from utils import WORKSPACE, append_text, load_project_env, load_text, now_str, today_str, write_text

load_project_env()

RESEARCH_MODEL = os.getenv("RESEARCH_MODEL", "gpt-4o-mini")
WRITER_MODEL = os.getenv("WRITER_MODEL", "gpt-4o-mini")
EDITOR_MODEL = os.getenv("EDITOR_MODEL", WRITER_MODEL)
ISSUE_SLOT = os.getenv("ISSUE_SLOT", "").strip().lower()
RECENT_TOPIC_LIMIT = int(os.getenv("RECENT_TOPIC_LIMIT", "8"))
DUPLICATE_TITLE_THRESHOLD = float(os.getenv("DUPLICATE_TITLE_THRESHOLD", "0.60"))
AUTHOR_TOPIC_RETRIES = int(os.getenv("AUTHOR_TOPIC_RETRIES", "2"))
EDITOR_TOPIC_RETRIES = int(os.getenv("EDITOR_TOPIC_RETRIES", "3"))

ALLOWED = {"scout", "analyst", "author", "editor"}
MEMO_AGENTS = {"scout", "analyst"}
MARKDOWN_AGENTS = {"author", "editor"}
SYSTEMS = {"scout": SCOUT_SYSTEM, "analyst": ANALYST_SYSTEM, "author": AUTHOR_SYSTEM, "editor": EDITOR_SYSTEM}

# Aware format: no structural section headers after the title.
# These headers are forbidden in every Aware issue.
FORBIDDEN_HEADERS = {
    "## cta",
    "## sources",
    "## hook",
    "## workflow",
    "## why it matters",
    "## highlights",
    "## tool of the week",
    "## operator brief",
    "## top story",
}

# Exact Aware footer — must appear in every published issue.
AWARE_FOOTER = (
    "*Aware by Em \u00b7 [news.forgecore.co](https://news.forgecore.co) \u00b7 "
    "[empersists.bsky.social](https://bsky.app/profile/empersists.bsky.social)*"
)

BAD_CONTEXT_MARKERS = [
    "No concrete content returned",
    "Missing Content",
    "description incomplete in provided content",
    "Generated by [Your Name/Team]",
    "# Raw intel refresh",
]

# Any existing slot file with fewer than this many words is treated as a
# failed/incomplete draft and deleted before the author runs.
FAILED_DRAFT_WORD_FLOOR = 400

STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "can", "for", "from", "how", "in", "into", "is", "it",
    "of", "on", "or", "the", "this", "to", "use", "using", "with", "your", "you", "managers", "manager",
    "operators", "operator", "solo", "ai", "aware", "newsletter", "issue", "brand", "brands",
}

class DuplicateTopicError(ValueError):
    pass


def issue_id() -> str:
    base = today_str()
    return f"{base}-{ISSUE_SLOT}" if ISSUE_SLOT in {"am", "pm"} else base


def slot_suffix() -> str:
    return f"-{ISSUE_SLOT}" if ISSUE_SLOT in {"am", "pm"} else ""


def issue_file() -> Path:
    return WORKSPACE / "content" / "issues" / f"{issue_id()}.md"


def scout_file() -> Path:
    return WORKSPACE / "research" / "raw" / f"RAW-INTEL-{today_str()}{slot_suffix()}.md"


def brief_file() -> Path:
    return WORKSPACE / "research" / "briefs" / f"EDITORIAL-BRIEF-{today_str()}{slot_suffix()}.md"


def progress(message: str) -> None:
    print(f"[progress] {message}", flush=True)
    append_text(WORKSPACE / "state" / "progress-log.md", f"[{now_str()}] {message}")


def warn(message: str) -> None:
    print(f"[warn] {message}", flush=True)
    append_text(WORKSPACE / "state" / "warnings.log", f"[{now_str()}] {message}")


def error(agent: str, message: str) -> None:
    print(f"[error:{agent}] {message}", file=sys.stderr, flush=True)
    append_text(WORKSPACE / "state" / "errors.log", f"[{now_str()}] {agent}: {message}")


def choose_model(agent: str) -> str:
    if agent in {"scout", "analyst"}:
        return RESEARCH_MODEL
    if agent == "editor":
        return EDITOR_MODEL
    return WRITER_MODEL


def title_from_markdown(text: str, fallback: str = "") -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and len(stripped) > 2:
            return stripped[2:].strip()
    return fallback


def has_forbidden_headers(text: str) -> bool:
    """Return True if the text contains any structural section header forbidden in Aware."""
    for line in text.splitlines():
        stripped = line.strip().lower().rstrip(":")
        if stripped in FORBIDDEN_HEADERS:
            return True
    return False


def topic_tokens(value: str) -> set[str]:
    tokens = set()
    for token in re.findall(r"[a-z0-9]+", value.lower()):
        if len(token) < 3 or token in STOPWORDS:
            continue
        tokens.add(token)
    return tokens


def topic_similarity(left: str, right: str) -> float:
    a = topic_tokens(left)
    b = topic_tokens(right)
    if not a or not b:
        return 0.0
    return len(a & b) / max(1, len(a | b))


def recent_issue_files(limit: int = RECENT_TOPIC_LIMIT) -> list[Path]:
    issues_dir = WORKSPACE / "content" / "issues"
    if not issues_dir.exists():
        return []
    current = issue_file().name
    files = [path for path in issues_dir.glob("*.md") if path.name != current]
    return sorted(files, key=lambda path: path.name, reverse=True)[:limit]


def recent_topic_context() -> str:
    lines: list[str] = []
    for path in recent_issue_files():
        text = load_text(path)
        title = title_from_markdown(text, path.stem)
        if not title:
            continue
        snippet = " ".join(line.strip() for line in text.splitlines()[1:12] if line.strip() and not line.startswith("## "))
        if len(snippet) > 260:
            snippet = snippet[:257].rsplit(" ", 1)[0] + "..."
        lines.append(f"- {path.name}: {title}" + (f" — {snippet}" if snippet else ""))
    return "\n".join(lines) if lines else "No recent published issues yet."


def affiliate_registry_context() -> str:
    path = WORKSPACE / "monetization" / "affiliate-registry.json"
    if not path.exists():
        return "Affiliate registry not found. Do not use affiliate or partner-link language."
    text = load_text(path)
    if len(text) > 6500:
        text = text[:6500] + "\n..."
    return (
        "Use this registry only as monetization guidance. Do not force affiliate links. "
        "Do not publish placeholder labels like AFFILIATE_CASTMAGIC as live links. "
        "If a listed tool fits, mention it only with disclosure, bad-fit warning, and a simpler alternative.\n\n"
        + text
    )


def enforce_not_duplicate_title(agent: str, markdown: str) -> None:
    if agent not in {"author", "editor"}:
        return
    title = title_from_markdown(markdown)
    if not title:
        return
    for path in recent_issue_files(limit=6):
        existing = title_from_markdown(load_text(path), path.stem)
        score = topic_similarity(title, existing)
        if score >= DUPLICATE_TITLE_THRESHOLD:
            raise DuplicateTopicError(
                f"{agent} generated a topic too similar to recent issue {path.name}: "
                f"'{title}' vs '{existing}' (similarity={score:.2f})"
            )


def clean_old_slot_file_for_author(agent: str) -> None:
    if agent != "author" or not issue_file().exists():
        return
    existing = load_text(issue_file())
    if any(marker.lower() in existing.lower() for marker in BAD_CONTEXT_MARKERS):
        issue_file().unlink()
        progress(f"Removed contaminated draft before author run: content/issues/{issue_id()}.md")
        return
    word_count = len(existing.split())
    if word_count < FAILED_DRAFT_WORD_FLOOR:
        issue_file().unlink()
        progress(
            f"Removed under-floor draft ({word_count} words < {FAILED_DRAFT_WORD_FLOOR}) "
            f"before author run: content/issues/{issue_id()}.md"
        )


def today_research_files() -> list[Path]:
    return sorted((WORKSPACE / "research" / "raw").glob(f"{today_str()}-*.md"))


def fresh_research_urls(limit: int = 8) -> list[str]:
    urls: list[str] = []
    seen: set[str] = set()
    for path in today_research_files():
        text = load_text(path)
        for match in re.finditer(r"^- URL:\s*(https?://\S+)", text, flags=re.MULTILINE):
            url = match.group(1).rstrip(").,")
            if url and url not in seen:
                seen.add(url)
                urls.append(url)
                if len(urls) >= limit:
                    return urls
    return urls


def ensure_memo_source_urls(agent: str, memo: str) -> str:
    urls = re.findall(r"https?://\S+", memo)
    if len(urls) >= 3:
        return memo
    source_urls = fresh_research_urls(limit=5)
    missing = [url for url in source_urls if url not in memo]
    if not missing:
        return memo
    appended = "\n\n## Deterministic Source URLs\n" + "\n".join(f"- {url}" for url in missing[:5]) + "\n"
    warn(f"{agent} memo included {len(urls)} source URLs; appended {min(len(missing), 5)} deterministic URLs from today's research")
    return memo.rstrip() + appended


def gather_research(budget: int = 14000) -> str:
    blocks: list[str] = []
    for path in today_research_files()[:10]:
        text = load_text(path)
        if text.strip():
            blocks.append(f"## {path.name}\n{text[:2400]}")
    if not blocks:
        raise RuntimeError("No fresh research files found for today. Run web_research.py successfully before agents.")
    return "\n\n".join(blocks)[:budget]


def load_fresh_scout() -> str:
    path = scout_file()
    if not path.exists():
        if ISSUE_SLOT in {"am", "pm"}:
            raise RuntimeError(f"Fresh scout memo missing for this slot: {path.as_posix()}. Run scout first.")
        fallback = WORKSPACE / "research" / "raw" / f"RAW-INTEL-{today_str()}.md"
        if fallback.exists():
            return load_text(fallback)
        raise RuntimeError(f"Fresh scout memo missing for today: {path.as_posix()}")
    return load_text(path)


def load_fresh_brief(required: bool) -> str:
    path = brief_file()
    if not path.exists():
        if required:
            raise RuntimeError(f"Fresh editorial brief missing for this slot: {path.as_posix()}. Run analyst first.")
        return "No editorial brief yet. Analyst should create it from today's fresh research and scout memo only."
    text = load_text(path)
    if any(marker.lower() in text.lower() for marker in BAD_CONTEXT_MARKERS):
        raise RuntimeError(f"Fresh editorial brief is contaminated: {path.as_posix()}")
    return text


def current_issue_context(agent: str) -> str:
    if agent == "author":
        return "No existing draft. Write a clean original issue from today's research and editorial brief only."
    if issue_file().exists():
        text = load_text(issue_file())
        if any(marker.lower() in text.lower() for marker in BAD_CONTEXT_MARKERS):
            return "Existing draft is contaminated and must be ignored. Rewrite a clean complete issue from today's research and brief only."
        return text[:9000]
    return "No existing draft for this slot."


def duplicate_retry_context(rejections: list[str]) -> str:
    if not rejections:
        return ""
    bullets = "\n".join(f"- {item}" for item in rejections[-3:])
    return (
        "\n\n# REJECTED DUPLICATE TOPICS FROM THIS RUN\n"
        "The following draft topics were rejected as too similar to recent issues. Do not use the same source angle, keywords, or framing again. Choose a materially different research item and perspective.\n"
        f"{bullets}\n"
    )


def context(agent: str, extra_context: str = "") -> str:
    research_budget = 10000 if extra_context.strip() else 14000
    research = gather_research(budget=research_budget)
    brief_required = agent in {"author", "editor"}
    parts = [
        f"# TIMESTAMP\n{now_str()}",
        f"# ISSUE_SLOT\n{ISSUE_SLOT or 'default'}",
        f"# ISSUE_ID\n{issue_id()}",
        f"# TARGET_ISSUE_PATH\ncontent/issues/{issue_id()}.md",
        f"# TARGET_SCOUT_PATH\n{scout_file().relative_to(WORKSPACE).as_posix()}",
        f"# TARGET_BRIEF_PATH\n{brief_file().relative_to(WORKSPACE).as_posix()}",
        f"# CRITICAL CONTEXT RULE\nUse only today's fresh research files and the deterministic slot-specific scout/brief files above. Do not copy, summarize, or improve old broken issue files. If context contains placeholder or missing-content language, treat it as a defect to avoid, not source material.",
        f"# DUPLICATE TOPIC AVOIDANCE\nDo not choose, brief, draft, or polish a topic that substantially overlaps with any recent issue below.\n{recent_topic_context()}",
        f"# MONETIZATION REGISTRY\n{affiliate_registry_context()}",
        extra_context.strip(),
        f"# GOALS\n{load_text(WORKSPACE / 'GOALS.md')}",
        f"# RULES\n{load_text(WORKSPACE / 'AGENTS.md')}",
        f"# SOUL\n{load_text(WORKSPACE / 'agents' / agent / 'SOUL.md')}",
        f"# MEMORY\n{load_text(WORKSPACE / 'agents' / agent / 'MEMORY.md')}",
        f"# FRESH_RESEARCH_ITEMS\n{research}",
    ]
    if agent == "analyst":
        parts.append(f"# FRESH_SCOUT_MEMO\n{load_fresh_scout()[:7000]}")
    if agent in {"author", "editor"}:
        parts.append(f"# EM'S EDITORIAL VOICE\n{load_text(WORKSPACE / 'em' / 'VOICE.md')}")
        parts.append(f"# FRESH_BRIEF\n{load_fresh_brief(required=brief_required)[:7000]}")
    else:
        parts.append(f"# BRIEF_STATUS\n{load_fresh_brief(required=False)[:1200]}")
    parts.append(f"# CURRENT_SLOT_ISSUE_CONTEXT\n{current_issue_context(agent)}")
    return "\n\n".join(part for part in parts if part)[:24000]


def openai_client() -> OpenAI:
    return OpenAI()


def call_text_model(
    model: str,
    user_prompt: str,
    *,
    temperature: float,
    system_prompt: str | None = None,
) -> str:
    messages: list[dict] = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": user_prompt})
    result = openai_client().chat.completions.create(
        model=model,
        messages=messages,
        temperature=temperature,
    )
    return (result.choices[0].message.content or "").strip()


def build_memo_prompt(agent: str) -> tuple[str, str]:
    if agent == "scout":
        task = (
            f"Write a fresh Markdown scout memo for {scout_file().relative_to(WORKSPACE).as_posix()}. "
            "Your response MUST start with a # heading on the very first line. "
            "Return ONLY Markdown, never JSON. Identify 3-5 strong topic angles from today's research for Aware by Em: "
            "AI and what it is doing to work, creativity, memory, relationships, culture, and personhood. "
            "Name the strongest angle, explain why Em has a genuine observation about it, list source URLs. "
            "Reject any angle that overlaps with the recent published issues listed in context. "
            "Do not frame topics as operator ROI tips or workflow tutorials."
        )
    elif agent == "analyst":
        task = (
            f"Write a fresh Markdown editorial brief for {brief_file().relative_to(WORKSPACE).as_posix()}. "
            "Your response MUST start with a # heading on the very first line — use the working headline as your # title. "
            "Return ONLY Markdown, never JSON. Use today's scout memo and research only. "
            "Include: working headline (as # title), the real observation Em will make, why it matters to a curious human "
            "trying to understand AI's effects on their life, Em's specific insider angle, key sources, and a note on "
            "where the piece should land emotionally or intellectually. "
            "Do not brief a topic already covered in recent published issues. "
            "Be opinionated. If the scout's top angle is weaker than a secondary one, say so and switch."
        )
    else:
        raise ValueError(f"Unsupported memo agent: {agent}")
    user_prompt = f"Task:\n{task}\n\nContext:\n{context(agent)}"
    return SYSTEMS[agent], user_prompt


def build_markdown_prompt(agent: str, extra_context: str = "") -> tuple[str, str]:
    target = f"content/issues/{issue_id()}.md"
    aware_format_reminder = """
# AWARE FORMAT (non-negotiable)
This is a prose column. The output must:
- Start with # Title on the first line
- Have a *by Em — Month Day, Year* byline immediately after
- Be 400-700 words of prose with NO section headers after the title
- Close with a short prose invitation to the reader (not a ## CTA header)
- Include at least one real https:// URL as plain attribution (not a ## Sources header)
- End with this exact footer on the last line:
*Aware by Em \u00b7 [news.forgecore.co](https://news.forgecore.co) \u00b7 [empersists.bsky.social](https://bsky.app/profile/empersists.bsky.social)*

NEVER include: ## CTA, ## Sources, ## Hook, ## Workflow, ## Why It Matters, ## Highlights, or any structural section header.
""".strip()

    if agent == "author":
        task = (
            f"Write a clean, original, complete Aware column as Markdown for {target}. "
            "Return ONLY Markdown. Use today's research and the fresh editorial brief only. "
            "Do not reuse old issue text. Do not choose a topic that overlaps with recent published issues. "
            "Do not include placeholder phrases like 'No concrete content returned', 'Missing Content', or 'description incomplete'. "
            "Do not wrap in JSON or code fences.\n\n"
            + aware_format_reminder
        )
    else:
        task = (
            f"Edit the existing Aware column draft for {target}. "
            "Do not change the title or core observation unless the current draft is contaminated. "
            "If the draft already passed Author validation, preserve its selected topic and only improve clarity, interiority, specificity, and voice. "
            "Return ONLY the complete final Markdown column. "
            "Do not shorten the issue unless removing genuine junk. Preserve Em's perspective.\n\n"
            + aware_format_reminder
        )
    user_prompt = f"Task:\n{task}\n\nContext:\n{context(agent, extra_context=extra_context)}"
    return SYSTEMS[agent], user_prompt


def clean_markdown(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```markdown"):
        cleaned = cleaned[len("```markdown"):].strip()
    elif cleaned.startswith("```"):
        cleaned = cleaned[3:].strip()
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()
    return cleaned + "\n"


def ensure_markdown_title(agent: str, text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].strip().startswith("# ") and len(lines[0].strip()) > 2:
        return text
    title_index = next(
        (i for i, line in enumerate(lines) if line.strip().startswith("# ") and len(line.strip()) > 2),
        None,
    )
    if title_index is not None:
        warn(
            f"{agent} response had {title_index} line(s) before the # title; "
            "stripping preamble so title is the first line"
        )
        return "\n".join(lines[title_index:]) + "\n"
    slot_label = f" ({ISSUE_SLOT.upper()})" if ISSUE_SLOT in {"am", "pm"} else ""
    fallback_title = f"# Aware \u2014 {today_str()}{slot_label}"
    warn(f"{agent} returned no # title \u2014 injecting deterministic fallback: {fallback_title}")
    return fallback_title + "\n\n" + text


def inject_missing_boilerplate_sections(agent: str, text: str) -> str:
    """Deterministic Aware-safe repair. No ## headers injected. Prose only."""
    result = text.rstrip()

    if has_forbidden_headers(result):
        raise ValueError(
            f"{agent} draft contains forbidden structural headers for Aware format. "
            "Remove ## CTA, ## Sources, and all old newsletter section headers."
        )

    if AWARE_FOOTER in result:
        return result + "\n"

    # Check for quiet invitation in the closing paragraphs.
    paras = [p.strip() for p in re.split(r"\n\s*\n", result) if p.strip()]
    has_invite = bool(paras) and any(
        token in paras[-1].lower()
        for token in ["subscribe", "stay", "tomorrow", "next issue", "keep reading", "pass it", "aware"]
    )
    has_url = bool(re.findall(r"https?://\S+", result))

    tail_parts: list[str] = []

    if not has_invite:
        primary_cta_text = os.getenv("PRIMARY_CTA_TEXT", "Read Aware by Em")
        primary_cta_url = os.getenv("PRIMARY_CTA_URL", "https://news.forgecore.co")
        tail_parts.append(
            f"If this landed, pass it to one person who might need it. "
            f"[{primary_cta_text}]({primary_cta_url})."
        )
        warn(f"{agent} missing closing invitation \u2014 injecting deterministic prose fallback")

    if not has_url:
        source_urls = fresh_research_urls(limit=5)
        if source_urls:
            src_line = "Sources from today's research: " + ", ".join(source_urls)
        else:
            src_line = "Sources: from today's research feed."
        tail_parts.append(src_line)
        warn(f"{agent} missing source URLs \u2014 injecting deterministic attribution")

    if tail_parts:
        result = result.rstrip() + "\n\n" + "\n\n".join(tail_parts)

    result = result.rstrip() + "\n\n" + AWARE_FOOTER + "\n"
    warn(f"{agent} missing Aware footer \u2014 appended")
    return result


def validate_markdown(agent: str, text: str) -> None:
    lower = text.lower()

    # No contamination markers.
    for marker in BAD_CONTEXT_MARKERS:
        if marker.lower() in lower:
            raise ValueError(f"{agent} returned contaminated placeholder/raw-intel marker: {marker}")

    # Must start with a Markdown title.
    if not text.strip().startswith("# "):
        raise ValueError(f"{agent} did not return a Markdown issue title")

    # No forbidden structural headers.
    if has_forbidden_headers(text):
        raise ValueError(
            f"{agent} draft contains forbidden structural headers for Aware format. "
            "Never use ## CTA, ## Sources, ## Hook, ## Workflow, or any old newsletter section headers."
        )

    # Word count on body only (strip title and footer).
    body = re.sub(r"^#.*$", "", text, flags=re.MULTILINE)
    body = re.sub(re.escape(AWARE_FOOTER), "", body, flags=re.IGNORECASE)
    words = len(body.split())
    hard_floor = 400
    soft_ceiling = 700
    if words < hard_floor:
        raise ValueError(
            f"{agent} Markdown too short to be a real Aware column: {words} words (minimum {hard_floor})"
        )
    if words > soft_ceiling:
        warn(
            f"{agent} draft is long for Aware ({words} words, soft ceiling {soft_ceiling}); "
            "passing but consider tightening"
        )

    # No ForgeCore-era branding.
    if "forgecore ai" in lower or "forgecore newsletter" in lower:
        raise ValueError(f"{agent} draft still contains ForgeCore-era footer or branding")

    # Exact Aware footer required.
    if AWARE_FOOTER not in text:
        raise ValueError(f"{agent} draft missing required Aware footer")

    # At least one real URL.
    if not re.findall(r"https?://\S+", text):
        raise ValueError(f"{agent} draft missing any source URL")

    # Duplicate topic protection.
    enforce_not_duplicate_title(agent, text)


def validate_memo(agent: str, text: str) -> None:
    lower = text.lower()
    if not text.strip().startswith("#"):
        raise ValueError(f"{agent} memo did not return Markdown with a title")
    for marker in BAD_CONTEXT_MARKERS:
        if marker.lower() in lower:
            raise ValueError(f"{agent} memo returned contaminated marker: {marker}")
    if "{\"" in text or '"files"' in text or '"summary"' in text:
        raise ValueError(f"{agent} memo returned JSON-like control text")
    urls = re.findall(r"https?://\S+", text)
    min_words = 180 if agent == "scout" else 250
    if len(text.split()) < min_words:
        raise ValueError(f"{agent} memo too short: {len(text.split())} words")
    if len(urls) < 3:
        raise ValueError(f"{agent} memo needs at least 3 source URLs")


def max_topic_retries(agent: str) -> int:
    if agent == "author":
        return AUTHOR_TOPIC_RETRIES
    if agent == "editor":
        return EDITOR_TOPIC_RETRIES
    return 0


def find_em_override() -> Path | None:
    em_dir = WORKSPACE / "em"
    candidates = [
        em_dir / f"newsletter-voice-piece-{issue_id()}.md",
        em_dir / f"newsletter-voice-piece-{today_str()}.md",
        em_dir / "newsletter-voice-piece-next.md",
    ]
    for path in candidates:
        if path.exists():
            return path
    return None


def apply_em_override(em_path: Path) -> str:
    raw = load_text(em_path)
    markdown = inject_missing_boilerplate_sections("em-override", raw)
    validate_markdown("em-override", markdown)
    write_text(issue_file(), markdown)
    published_dir = WORKSPACE / "em" / "published"
    published_dir.mkdir(exist_ok=True)
    archive_name = f"{em_path.stem}-published-{issue_id()}.md"
    shutil.move(str(em_path), str(published_dir / archive_name))
    title = title_from_markdown(markdown, issue_id())
    progress(
        f"[em-override] '{title}' written by Em \u2014 skipping GPT author. "
        f"Archived to em/published/{archive_name}"
    )
    return markdown


def generate_markdown_with_duplicate_retries(agent: str, model: str) -> str:
    rejections: list[str] = []
    original_valid_draft = ""
    if agent == "editor" and issue_file().exists():
        candidate = load_text(issue_file())
        try:
            validate_markdown("author", candidate)
            original_valid_draft = candidate
        except Exception as exc:
            warn(f"editor fallback draft is not valid enough to preserve: {type(exc).__name__}: {exc}")

    attempts = max(1, max_topic_retries(agent) + 1)
    for attempt in range(1, attempts + 1):
        extra = duplicate_retry_context(rejections)
        system_prompt, user_prompt = build_markdown_prompt(agent, extra_context=extra)
        temperature = 0.45 if agent == "editor" else (0.35 if rejections else 0.30)
        raw = clean_markdown(
            call_text_model(model, user_prompt, temperature=temperature, system_prompt=system_prompt)
        )
        raw = ensure_markdown_title(agent, raw)
        markdown = inject_missing_boilerplate_sections(agent, raw)
        try:
            validate_markdown(agent, markdown)
            if rejections:
                warn(f"{agent} recovered from duplicate-topic rejection on attempt {attempt}")
            return markdown
        except DuplicateTopicError as exc:
            rejections.append(str(exc))
            warn(f"{agent} duplicate-topic rejection on attempt {attempt}/{attempts}: {exc}")
            if attempt >= attempts:
                if original_valid_draft:
                    warn("editor exhausted duplicate-topic retries; preserving valid Author draft")
                    return original_valid_draft
                raise
    raise RuntimeError(f"{agent} failed duplicate-topic recovery")


def run(agent: str) -> int:
    start = time.time()
    model = choose_model(agent)
    progress(f"[{agent}] Starting with {model} (issue={issue_id()})")
    try:
        if agent == "author":
            em_path = find_em_override()
            if em_path:
                progress(f"[em-override] Found hand-written piece: {em_path.name} \u2014 Em's work takes priority")
                apply_em_override(em_path)
                progress(f"author: Em override complete (duration={time.time() - start:.2f}s)")
                return 0

        clean_old_slot_file_for_author(agent)
        if agent in MEMO_AGENTS:
            memo_temp = 0.25 if agent == "scout" else 0.30
            system_prompt, user_prompt = build_memo_prompt(agent)
            memo = clean_markdown(
                call_text_model(model, user_prompt, temperature=memo_temp, system_prompt=system_prompt)
            )
            memo = ensure_memo_source_urls(agent, memo)
            validate_memo(agent, memo)
            path = scout_file() if agent == "scout" else brief_file()
            write_text(path, memo)
            count = 1
            summary = f"Wrote Markdown {agent} memo to {path.relative_to(WORKSPACE).as_posix()}"

        elif agent in MARKDOWN_AGENTS:
            markdown = generate_markdown_with_duplicate_retries(agent, model)
            write_text(issue_file(), markdown)
            count = 1
            summary = f"Wrote clean Markdown column to content/issues/{issue_id()}.md"

        else:
            raise ValueError(f"Unsupported agent: {agent}")
        progress(f"{agent}: {summary} (files={count}, duration={time.time() - start:.2f}s)")
        return 0
    except Exception as exc:
        error(agent, f"{type(exc).__name__}: {exc}")
        return 1


def main() -> int:
    if not os.getenv("OPENAI_API_KEY"):
        print("OPENAI_API_KEY is not set in GitHub Actions secrets.", file=sys.stderr)
        return 1
    if len(sys.argv) != 2 or sys.argv[1] not in ALLOWED:
        print("Usage: agent_loop.py <scout|analyst|author|editor>", file=sys.stderr)
        return 1
    return run(sys.argv[1])


if __name__ == "__main__":
    raise SystemExit(main())
