#!/usr/bin/env python3
"""improvement_loop.py - Targeted quality improvement pass for the current ForgeCore issue slot."""
from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path
from typing import Any

from openai import OpenAI

from templates.system_prompts import EDITOR_SYSTEM
from utils import (
    WORKSPACE,
    append_text,
    artifact_suffix_for_issue,
    issue_path_for_today,
    load_project_env,
    load_text,
    now_str,
    today_str,
    write_text,
)

load_project_env()

EDITOR_MODEL = os.getenv("EDITOR_MODEL", "gpt-4o-mini")
MAX_CONTEXT_CHARS = int(os.getenv("MAX_CONTEXT_CHARS", "22000"))
MAX_TARGETED_REWRITE_ITEMS = int(os.getenv("MAX_TARGETED_REWRITE_ITEMS", "6"))
REQUIRED_CTA_URL = "https://forgecore-newsletter.beehiiv.com/"
REQUIRED_SPONSOR_EMAIL = "sponsors@forgecore.co"
REQUIRED_ISSUE_SECTIONS = [
    "## Hook",
    "## Top Story",
    "## Why It Matters",
    "## Highlights",
    "## Tool of the Week",
    "## Workflow",
    "## CTA",
    "## Sources",
]

STATE_DIR = WORKSPACE / "state"
IMPROVE_LOG = STATE_DIR / "improvement-log.md"
EDITORIAL_LESSONS = STATE_DIR / "editorial-lessons.md"

BAD_MARKERS = (
    "no concrete content returned",
    "missing content",
    "description incomplete",
    "description incomplete in provided content",
    "generated by [your name/team]",
    "raw intel",
)

TRUST_WARNING_PATTERNS = (
    r"\bdo not use\b",
    r"\bdon't use\b",
    r"\bavoid this\b",
    r"\bnot a fit\b",
    r"\bwho should avoid\b",
    r"\buse .* instead if\b",
)

TOOL_RECOMMENDATION_PATTERNS = (
    r"\btool of the week\b",
    r"\brecommend\b",
    r"\buse [A-Z][A-Za-z0-9 ._-]{2,}\b",
    r"\btry [A-Z][A-Za-z0-9 ._-]{2,}\b",
)


def log(message: str) -> None:
    append_text(IMPROVE_LOG, f"[{now_str()}] {message}")


def err(message: str) -> None:
    append_text(STATE_DIR / "errors.log", f"[{now_str()}] improvement_loop: {message}")
    log(f"[ERROR] {message}")


def emit_result(*, changed: bool, issue_path: str | None, reason: str) -> None:
    print(json.dumps({"changed": changed, "issue_path": issue_path, "reason": reason}))


def load_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except Exception:
        return None


def critic_path(issue_path: Path) -> Path:
    return STATE_DIR / f"critic-review-{artifact_suffix_for_issue(issue_path)}.json"


def gate_path(issue_path: Path) -> Path:
    return STATE_DIR / f"quality-gate-{artifact_suffix_for_issue(issue_path)}.json"


def extract_gate_errors(gate: dict[str, Any] | None) -> list[str]:
    if not gate:
        return []
    checks = gate.get("checks", {}) if isinstance(gate.get("checks"), dict) else {}
    values = checks.get("errors") or gate.get("errors") or []
    return [str(item) for item in values if str(item).strip()]


def extract_gate_warnings(gate: dict[str, Any] | None) -> list[str]:
    if not gate:
        return []
    checks = gate.get("checks", {}) if isinstance(gate.get("checks"), dict) else {}
    values = checks.get("warnings") or gate.get("warnings") or []
    return [str(item) for item in values if str(item).strip()]


def extract_critic_items(critic: dict[str, Any] | None) -> list[str]:
    if not critic:
        return []
    items: list[str] = []
    for key in ["must_fix", "rewrite_plan", "weaknesses", "weak_categories"]:
        value = critic.get(key)
        if isinstance(value, list):
            items.extend(str(item) for item in value if str(item).strip())
        elif isinstance(value, str) and value.strip():
            items.append(value.strip())
    return items[:MAX_TARGETED_REWRITE_ITEMS]


def contains_bad_marker(text: str) -> bool:
    lower = text.lower()
    return any(marker in lower for marker in BAD_MARKERS)


def hook_word_count(markdown: str) -> int:
    match = re.search(r"^## Hook\s*\n(.+?)(?=^## |\Z)", markdown, flags=re.MULTILINE | re.DOTALL)
    if not match:
        return 0
    return len(re.findall(r"\b\w+\b", match.group(1)))


def section_body(text: str, section: str) -> str:
    match = re.search(rf"^{re.escape(section)}\n(.+?)(?=^## |\Z)", text, flags=re.MULTILINE | re.DOTALL)
    return match.group(1).strip() if match else ""


def replace_section(markdown: str, section: str, replacement_body: str) -> str:
    pattern = rf"^{re.escape(section)}\n(.+?)(?=^## |\Z)"
    replacement = f"{section}\n{replacement_body.strip()}\n\n"
    if re.search(pattern, markdown, flags=re.MULTILINE | re.DOTALL):
        return re.sub(pattern, replacement.rstrip(), markdown, count=1, flags=re.MULTILINE | re.DOTALL)
    return markdown.rstrip() + "\n\n" + replacement


def unique_urls(text: str) -> list[str]:
    urls = [u.rstrip(").,") for u in re.findall(r"https?://\S+", text)]
    return list(dict.fromkeys(urls))


def fresh_research_urls(limit: int = 6) -> list[str]:
    urls: list[str] = []
    seen: set[str] = set()
    for path in sorted((WORKSPACE / "research" / "raw").glob(f"{today_str()}-*.md")):
        text = load_text(path)
        for match in re.finditer(r"^- URL:\s*(https?://\S+)", text, flags=re.MULTILINE):
            url = match.group(1).rstrip(").,")
            if url and url not in seen:
                seen.add(url)
                urls.append(url)
                if len(urls) >= limit:
                    return urls
    return urls


def has_tool_recommendation(markdown: str) -> bool:
    tool_section = section_body(markdown, "## Tool of the Week")
    return bool(tool_section and any(re.search(p, tool_section, flags=re.IGNORECASE | re.MULTILINE) for p in TOOL_RECOMMENDATION_PATTERNS))


def has_trust_warning(markdown: str) -> bool:
    return any(re.search(p, markdown, flags=re.IGNORECASE | re.MULTILINE) for p in TRUST_WARNING_PATTERNS)


def workflow_has_code_block(markdown: str) -> bool:
    workflow = section_body(markdown, "## Workflow")
    return "```" in workflow


def cta_is_complete(markdown: str) -> bool:
    cta = section_body(markdown, "## CTA")
    if len(cta.split()) < 8:
        return False
    lower = cta.lower()
    return REQUIRED_CTA_URL in cta and REQUIRED_SPONSOR_EMAIL in cta and "sponsor this issue" in lower


def ensure_required_sections(markdown: str) -> str:
    current = markdown.strip()
    if not current.startswith("# "):
        current = "# ForgeCore Operator Workflow\n\n" + current
    for section in REQUIRED_ISSUE_SECTIONS:
        if section not in current:
            current = current.rstrip() + f"\n\n{section}\n"
    return current.rstrip() + "\n"


def ensure_tool_recommendation(markdown: str) -> str:
    if has_tool_recommendation(markdown):
        return markdown
    body = section_body(markdown, "## Tool of the Week")
    addition = (
        "\n\nRecommended tool: use Zapier Agents when the workflow needs repeatable monitoring, routing, or follow-up across apps. "
        "It fits solo operators who already use Zapier and want a practical automation layer without building custom infrastructure. "
        "For a simpler version, use ChatGPT or your existing workspace assistant to draft the checklist first, then only automate the steps that repeat every week."
    )
    return replace_section(markdown, "## Tool of the Week", (body + addition).strip())


def ensure_trust_warning(markdown: str) -> str:
    if has_trust_warning(markdown):
        return markdown
    body = section_body(markdown, "## Tool of the Week")
    addition = (
        "\n\nDo not use this if the workflow is still changing every day, if the task requires sensitive customer data you have not reviewed, "
        "or if a simple saved prompt would solve the problem. Automate only after the manual process is clear."
    )
    return replace_section(markdown, "## Tool of the Week", (body + addition).strip())


def ensure_workflow_block(markdown: str) -> str:
    if workflow_has_code_block(markdown):
        return markdown
    body = section_body(markdown, "## Workflow")
    block = """
```text
Weekly operator automation checklist:
1. Name the repeatable task you want to reduce.
2. List the trigger, input, decision, output, and owner.
3. Run the task manually once and save the exact steps.
4. Ask AI to turn those steps into a checklist, prompt, or automation map.
5. Automate only the stable handoff, then review the first three outputs before trusting it.
```
""".strip()
    return replace_section(markdown, "## Workflow", (body + "\n\n" + block).strip())


def ensure_sources(markdown: str) -> str:
    urls = unique_urls(markdown)
    source_lines_existing = [line for line in section_body(markdown, "## Sources").splitlines() if line.strip()]
    if len(urls) >= 3 and len(source_lines_existing) >= 3:
        return markdown
    research_urls = fresh_research_urls(limit=6)
    merged = list(dict.fromkeys(urls + research_urls))[:6]
    if len(merged) < 3:
        merged = urls[:6]
    source_lines = "\n".join(f"- {url}" for url in merged if url)
    return replace_section(markdown, "## Sources", source_lines or "- Source URLs unavailable from this run.")


def ensure_cta(markdown: str) -> str:
    if cta_is_complete(markdown):
        return markdown
    body = section_body(markdown, "## CTA")
    body = re.sub(r"\s+", " ", body).strip()
    if len(body.split()) < 8 or "sponsor this issue" not in body.lower():
        body = (
            "Run this workflow once this week and measure whether it gives you a clearer tool decision, faster research cycle, or better follow-up system. "
            f"Subscribe for more operator-grade AI workflows: {REQUIRED_CTA_URL}"
        )
    if REQUIRED_CTA_URL not in body:
        body += f" Subscribe here: {REQUIRED_CTA_URL}"
    if REQUIRED_SPONSOR_EMAIL not in body or "sponsor this issue" not in body.lower():
        body += f" Sponsor this issue: email {REQUIRED_SPONSOR_EMAIL}."
    return replace_section(markdown, "## CTA", body)


def enforce_deterministic_guardrails(markdown: str) -> tuple[str, list[str]]:
    changed: list[str] = []
    current = markdown
    updates = [
        ("required sections", ensure_required_sections),
        ("tool recommendation", ensure_tool_recommendation),
        ("trust warning", ensure_trust_warning),
        ("workflow code block", ensure_workflow_block),
        ("source URLs", ensure_sources),
        ("CTA", ensure_cta),
    ]
    for label, fn in updates:
        updated = fn(current)
        if updated != current:
            changed.append(label)
            current = updated
    return current, changed


def lesson_rule_from_item(item: str) -> str:
    lower = item.lower()
    if "hook" in lower:
        return "Start the Hook with the operator outcome or decision, not a product announcement."
    if "headline" in lower or "title" in lower:
        return "Make the headline name the workflow, operator, tool choice, or measurable outcome."
    if "workflow" in lower or "step" in lower:
        return "Turn vague advice into 3-6 named steps plus one prompt, checklist, config, or command block."
    if "specific" in lower or "generic" in lower:
        return "Name the exact operator persona, job-to-be-done, tool stack, and tradeoff."
    if "source" in lower or "unsupported" in lower:
        return "Remove unsupported claims or tie them to a real source URL from today's research."
    if "cta" in lower:
        return "CTA must tell the reader what to try this week and include subscribe plus sponsor links."
    if "tradeoff" in lower:
        return "Include practical tradeoffs: cost, speed, privacy, quality, maintenance, or learning curve."
    if "placeholder" in lower or "no concrete content" in lower:
        return "When placeholder text appears, rewrite the whole issue from scratch; never edit around it."
    return "Convert weak prose into a concrete operator decision, workflow, or tool tradeoff."


def persist_editorial_lessons(issue_path: Path, critic: dict[str, Any] | None, gate: dict[str, Any] | None, changed: bool, reason: str) -> None:
    critic_items = extract_critic_items(critic)
    gate_errors = extract_gate_errors(gate)
    gate_warnings = extract_gate_warnings(gate)
    priorities = (critic_items + gate_errors + gate_warnings)[:MAX_TARGETED_REWRITE_ITEMS]
    if not priorities and not changed:
        return
    lines = [
        f"## {now_str()} — {issue_path.as_posix()}",
        f"- Improvement result: {'changed' if changed else 'unchanged'} ({reason})",
    ]
    if critic:
        lines.append(f"- Critic score: {critic.get('overall_score', 'unknown')} | verdict: {critic.get('verdict', 'unknown')}")
    if priorities:
        lines.append("- Weaknesses found:")
        for item in priorities:
            lines.append(f"  - {item}")
        lines.append("- Rules for future issues:")
        seen_rules: set[str] = set()
        for item in priorities:
            rule = lesson_rule_from_item(item)
            if rule not in seen_rules:
                seen_rules.add(rule)
                lines.append(f"  - {rule}")
    else:
        lines.append("- Rule for future issues: Preserve the structure that passed and keep the workflow specific.")
    append_text(EDITORIAL_LESSONS, "\n".join(lines))


def call_editor(prompt: str) -> str:
    client = OpenAI()
    result = client.chat.completions.create(
        model=EDITOR_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )
    return (result.choices[0].message.content or "").strip()


def clean_markdown(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```markdown"):
        cleaned = cleaned[len("```markdown"):].strip()
    elif cleaned.startswith("```"):
        cleaned = cleaned[3:].strip()
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()
    return cleaned.strip() + "\n"


def build_prompt(issue_path: Path, issue_text: str, critic: dict[str, Any] | None, gate: dict[str, Any] | None) -> str:
    critic_items = extract_critic_items(critic)
    gate_errors = extract_gate_errors(gate)
    gate_warnings = extract_gate_warnings(gate)
    priorities = critic_items + gate_errors + gate_warnings
    if contains_bad_marker(issue_text):
        priorities.insert(0, "Known placeholder/garbage text is present. Do a full rewrite from scratch and do not reuse any sentence from the current issue.")
    if hook_word_count(issue_text) < 20:
        priorities.insert(0, "Hook is missing or weak. Write a 20-45 word Hook that names the operator, the workflow decision, and the practical outcome.")
    if not priorities:
        priorities = ["Improve headline, hook, specificity, operator usefulness, and workflow clarity."]

    priority_block = "\n".join(f"- {item}" for item in priorities[:MAX_TARGETED_REWRITE_ITEMS])
    lessons = load_text(EDITORIAL_LESSONS)[-5000:]
    return (
        EDITOR_SYSTEM
        + "\n\n# TARGETED IMPROVEMENT TASK\n"
        + f"Rewrite the issue at {issue_path.as_posix()} so it is more publishable.\n"
        + "Return ONLY the complete final Markdown issue. Do not wrap it in JSON. Do not include notes.\n"
        + "Never include placeholder phrases such as 'No concrete content returned', 'Missing Content', or 'description incomplete'.\n\n"
        + "## Must-fix priorities\n"
        + priority_block
        + "\n\n## Recent editorial lessons to apply\n"
        + (lessons or "No prior lessons yet.")
        + "\n\n## Current issue\n"
        + issue_text[:MAX_CONTEXT_CHARS]
    )


def build_hard_rewrite_prompt(issue_path: Path, contaminated_text: str, critic: dict[str, Any] | None, gate: dict[str, Any] | None) -> str:
    critic_items = extract_critic_items(critic)
    gate_errors = extract_gate_errors(gate)
    priorities = "\n".join(f"- {item}" for item in (critic_items + gate_errors)[:MAX_TARGETED_REWRITE_ITEMS])
    return (
        EDITOR_SYSTEM
        + "\n\n# HARD REWRITE REQUIRED\n"
        + f"The issue at {issue_path.as_posix()} still contains placeholder or structurally weak content.\n"
        + "Rewrite the ENTIRE issue from scratch. Do not reuse sentences from the current draft.\n"
        + "Return ONLY complete Markdown with this exact structure:\n"
        + "# Title\n## Hook\n## Top Story\n## Why It Matters\n## Highlights\n## Tool of the Week\n## Workflow\n## CTA\n## Sources\n\n"
        + "Hard requirements:\n"
        + "- Hook must be 20-45 words and must not be empty.\n"
        + "- Do not include: No concrete content returned, Missing Content, description incomplete, raw intel.\n"
        + "- Include 750+ words, 3+ real source URLs, one workflow code/checklist block, Beehiiv subscribe URL, and sponsors@forgecore.co.\n"
        + "- Make it useful to a solo operator; no generic AI news recap.\n\n"
        + "Must-fix context:\n"
        + (priorities or "- Replace placeholder text and strengthen Hook.")
        + "\n\nCurrent contaminated draft, for topic only. Do not copy wording:\n"
        + contaminated_text[:9000]
    )


def structurally_valid(markdown: str) -> tuple[bool, str]:
    if not markdown.lstrip().startswith("# "):
        return False, "missing title"
    missing = [section for section in REQUIRED_ISSUE_SECTIONS if section not in markdown]
    if missing:
        return False, "missing sections: " + ", ".join(missing)
    if contains_bad_marker(markdown):
        return False, "contains known placeholder/garbage marker"
    if hook_word_count(markdown) < 20:
        return False, f"hook too short: {hook_word_count(markdown)} words"
    if len(markdown.split()) < 500:
        return False, f"too short: {len(markdown.split())} words"
    return True, "ok"


def improve_issue(issue_path: Path) -> tuple[bool, str]:
    original = load_text(issue_path)
    if not original.strip():
        return False, "empty issue payload"
    critic = load_json(critic_path(issue_path))
    gate = load_json(gate_path(issue_path))
    try:
        raw = call_editor(build_prompt(issue_path, original, critic, gate))
        improved = clean_markdown(raw)
        improved, deterministic_changes = enforce_deterministic_guardrails(improved)
        if deterministic_changes:
            log("Applied deterministic guardrails: " + ", ".join(deterministic_changes))
        ok, reason = structurally_valid(improved)
        if not ok and (contains_bad_marker(improved) or hook_word_count(improved) < 20 or contains_bad_marker(original)):
            log(f"Hard rewrite triggered for {issue_path.as_posix()}: {reason}")
            raw = call_editor(build_hard_rewrite_prompt(issue_path, improved, critic, gate))
            improved = clean_markdown(raw)
            improved, deterministic_changes = enforce_deterministic_guardrails(improved)
            if deterministic_changes:
                log("Applied deterministic guardrails after hard rewrite: " + ", ".join(deterministic_changes))
            ok, reason = structurally_valid(improved)
        if not ok:
            persist_editorial_lessons(issue_path, critic, gate, False, f"invalid improved markdown: {reason}")
            return False, f"invalid improved markdown: {reason}"
        if improved.strip() == original.strip():
            persist_editorial_lessons(issue_path, critic, gate, False, "rewrite is identical")
            return False, "rewrite is identical"
        write_text(issue_path, improved)
        persist_editorial_lessons(issue_path, critic, gate, True, "rewritten issue saved")
        return True, "rewritten issue saved"
    except Exception as exc:
        err(f"{type(exc).__name__}: {exc}")
        persist_editorial_lessons(issue_path, critic, gate, False, f"{type(exc).__name__}: {exc}")
        return False, f"{type(exc).__name__}: {exc}"


def main() -> int:
    path = issue_path_for_today()
    if not path.exists():
        emit_result(changed=False, issue_path=path.as_posix(), reason="no issue for slot")
        return 0
    log(f"Improving {path.as_posix()} using targeted critic/gate guidance ...")
    changed, reason = improve_issue(path)
    if changed:
        log(f"Improved {path.as_posix()}: {reason}")
    else:
        log(f"No improvement applied to {path.as_posix()}: {reason}")
    emit_result(changed=changed, issue_path=path.as_posix(), reason=reason)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
