#!/usr/bin/env python3
"""Research quality gate for ForgeCore.

Runs immediately after web_research.py and before any agents.
Fails fast when today's research is missing, contaminated, too thin, or too
single-source to support an operator-grade issue.
"""
from __future__ import annotations

import json
import os
import re
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse

from utils import WORKSPACE, append_text, now_str, today_str, write_text

ISSUE_SLOT = os.getenv("ISSUE_SLOT", "").strip().lower()
STATE_DIR = WORKSPACE / "state"
RAW_DIR = WORKSPACE / "research" / "raw"
ARTIFACT_PATH = STATE_DIR / f"research-quality-{today_str()}{('-' + ISSUE_SLOT) if ISSUE_SLOT in {'am', 'pm'} else ''}.json"

MIN_RESEARCH_FILES = int(os.getenv("MIN_RESEARCH_FILES", "3"))
MIN_TOTAL_URLS = int(os.getenv("MIN_RESEARCH_URLS", "5"))
MIN_UNIQUE_DOMAINS = int(os.getenv("MIN_RESEARCH_DOMAINS", "3"))
MIN_OPERATOR_SIGNALS = int(os.getenv("MIN_OPERATOR_SIGNALS", "4"))
MAX_SINGLE_DOMAIN_SHARE = float(os.getenv("MAX_SINGLE_DOMAIN_SHARE", "0.65"))

BAD_MARKERS = (
    "no concrete content returned",
    "missing content",
    "description incomplete",
    "description incomplete in provided content",
    "placeholder_image.png",
    "example.com",
    "generated by [your name/team]",
)

BLOCKED_DOMAINS = (
    "ollama.com",
)

OPERATOR_TERMS = (
    "workflow",
    "automation",
    "automate",
    "operator",
    "founder",
    "creator",
    "consultant",
    "agency",
    "small business",
    "lead",
    "sales",
    "support",
    "marketing",
    "content",
    "email",
    "crm",
    "zapier",
    "make",
    "airtable",
    "notion",
    "hubspot",
    "canva",
    "descript",
    "beehiiv",
    "prompt",
    "playbook",
    "checklist",
    "roi",
    "time saved",
)


def log(message: str) -> None:
    append_text(STATE_DIR / "research-quality-log.md", f"[{now_str()}] {message}")


def today_research_files() -> list[Path]:
    return sorted(RAW_DIR.glob(f"{today_str()}-*.md"))


def extract_urls(text: str) -> list[str]:
    urls: list[str] = []
    for match in re.finditer(r"https?://[^\s)\]>]+", text):
        urls.append(match.group(0).rstrip(".,)]"))
    return urls


def domain_for(url: str) -> str:
    host = urlparse(url).netloc.lower()
    if host.startswith("www."):
        host = host[4:]
    return host


def count_operator_signals(text: str) -> int:
    lower = text.lower()
    return sum(1 for term in OPERATOR_TERMS if term in lower)


def validate() -> tuple[bool, dict]:
    files = today_research_files()
    errors: list[str] = []
    warnings: list[str] = []
    all_urls: list[str] = []
    domains: list[str] = []
    operator_signal_count = 0
    total_words = 0
    contaminated_files: list[str] = []

    if len(files) < MIN_RESEARCH_FILES:
        errors.append(f"Expected at least {MIN_RESEARCH_FILES} fresh research files for {today_str()}, found {len(files)}")

    for path in files:
        text = path.read_text(encoding="utf-8")
        total_words += len(text.split())
        lower = text.lower()
        bad_hits = [marker for marker in BAD_MARKERS if marker in lower]
        if bad_hits:
            contaminated_files.append(f"{path.as_posix()} ({', '.join(bad_hits[:3])})")
        operator_signal_count += count_operator_signals(text)
        urls = extract_urls(text)
        all_urls.extend(urls)
        domains.extend(domain_for(url) for url in urls if domain_for(url))

    unique_urls = sorted(set(all_urls))
    unique_domains = sorted(set(domains))
    domain_counts = Counter(domains)
    blocked_hits = [domain for domain in unique_domains if any(domain == blocked or domain.endswith('.' + blocked) for blocked in BLOCKED_DOMAINS)]

    if contaminated_files:
        errors.append("Research contains placeholder/meta contamination: " + "; ".join(contaminated_files[:4]))
    if len(unique_urls) < MIN_TOTAL_URLS:
        errors.append(f"Expected at least {MIN_TOTAL_URLS} unique source URLs, found {len(unique_urls)}")
    if len(unique_domains) < MIN_UNIQUE_DOMAINS:
        errors.append(f"Expected at least {MIN_UNIQUE_DOMAINS} unique source domains, found {len(unique_domains)}")
    if blocked_hits:
        errors.append("Research includes blocked stale domains: " + ", ".join(blocked_hits))
    if operator_signal_count < MIN_OPERATOR_SIGNALS:
        errors.append(f"Expected at least {MIN_OPERATOR_SIGNALS} operator/workflow signals, found {operator_signal_count}")
    if total_words < 700:
        errors.append(f"Research corpus too thin: {total_words} words")

    if domains:
        top_domain, top_count = domain_counts.most_common(1)[0]
        share = top_count / max(1, len(domains))
        if share > MAX_SINGLE_DOMAIN_SHARE:
            errors.append(f"Research overconcentrated on one domain: {top_domain} = {share:.0%} of URLs")
    else:
        warnings.append("No domains detected from research URLs")

    payload = {
        "passed": not errors,
        "date": today_str(),
        "issue_slot": ISSUE_SLOT or "default",
        "research_file_count": len(files),
        "word_count": total_words,
        "unique_url_count": len(unique_urls),
        "unique_domain_count": len(unique_domains),
        "operator_signal_count": operator_signal_count,
        "domains": unique_domains[:25],
        "errors": errors,
        "warnings": warnings,
        "artifact_path": ARTIFACT_PATH.as_posix(),
    }
    return not errors, payload


def main() -> int:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    passed, payload = validate()
    write_text(ARTIFACT_PATH, json.dumps(payload, indent=2) + "\n")
    if passed:
        log(f"Research quality PASSED for {payload['issue_slot']} with {payload['research_file_count']} files, {payload['unique_url_count']} URLs, {payload['unique_domain_count']} domains")
        print(json.dumps(payload))
        return 0
    log("Research quality FAILED: " + "; ".join(payload["errors"]))
    print(json.dumps(payload, indent=2))
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
